- name: Install apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
    id: "{{ ubuntu_docker_repo_key[ansible_distribution_release] }}"

- name: install docker repo
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable"
    state: present

- name: install docker
  apt:
    name:
      - "docker-ce{{ docker_version|ternary('=' ~ docker_version, '') }}"
      - "docker-ce-cli{{ docker_version|ternary('=' ~ docker_version, '') }}"
    state: present
    update_cache: yes

- name: install thin provisioning tools
  apt:
    name: thin-provisioning-tools
    state: present
